import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'primeicons/primeicons.css';
import "./globals.css";
import Topbar from "@/components/Topbar";
import Appbar from "@/components/Appbar";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Topbar />
        <div className="w-full -z-10 px-5 py-7 flex gap-5 ">
          <Appbar />
          <main className="w-full overflow-x-hidden p-2">
            <ScrollArea className='h-[calc(100vh-8.4rem)] px-2'>
              {children}
            </ScrollArea>
          </main>
        </div>
      </body>
    </html>
  );
}
